### ISSUE TITLE
How can one download entire RLCMS dataset at 30m for each year (1987-2017)?

### ISSUE THREAD

**Issue by j-johanness** [Servir-Mekong/RLCMS#1]
Dear SERVIR-Mekong,

I am a researcher investigating land cover dynamics in the mainland Southeast Asian region. Very recently, I have read about your amazing work in [Saah et al (2020)](https://www.sciencedirect.com/science/article/pii/S0303243419306270) which introduces a novel method of performing land cover classification using primitives. I believe this harmonized, long-term land cover monitoring system has immense potential for researchers and conservation practitioners working in the region.

As such, I am asking if there is a way to acquire the annual land cover maps at 30 m for the entire mapped region (i.e. mainland Southeast Asia). The reason I am asking is because I have found that on the [online RLCMS tool version 2](https://rlcms-servir.adpc.net/en/landcover/v2/), when I try and download the map for the whole region, I am unsuccessful in getting the data at 30 m. The exports were scaled up to 1 km resolution, and if I used a smaller box extent, 500 m and even 200 m. Only when I specify a small-enough box extent will I be able to get the dataset at 30 m resolution. I suspect this is due to some automatic pyramiding of the raster dataset when end-users such as myself are downloading the dataset from the online RLCMS tool.

I have visited your [GitHub](https://github.com/Servir-Mekong/landcoverPortal) and [Google Git](https://earthengine.googlesource.com/RLCMS/+/master) repositories, and added your Google Earth Engine code repository to my own GitHub and GEE accounts, but cannot find the correct file pathway as to where these annual land cover datasets (1987-2017) version 2 can be found. 

### My question is this;

Is there any way that I can download the annual land cover maps for each year for the entire mainland Southeast Asia? Instead of having to tesselate the region into small squares, and then downloading the annual land cover information one at a time, before mosaicking them together to get the annual land cover maps ( x 30 years, 1987 - 2017).

I definitely will credit your organization and its members ( e.g @biplovbhandari , @KMarkert and @apoortinga ) accordingly when using the dataset, as they have put in many hours of tremendous work into developing this instrumental dataset. Thank you kindly, I hope to hear from you soon.

**Comment by KMarkert** [comment]
Hi @j-johanness 👋 

How are you trying to initiate the download? Via a link or to your Google Drive?

Basically, there are restrictions on download using a link. So if you want everything in one file at 30m resolution the best option would be to export to your Google Drive and then download the file from your Google Drive.

If you have not tried that, please do so. If you have and it still does not work, let us know here and we can figure something out.

**Comment by j-johanness** [comment]
Hi there @KMarkert  :)

Thank you for your warm and prompt response! So far, in my attempts to download the RLCMS data, I have only been successful when I initiate the download via a link. Thank you for clarifying that there are restrictions when using that method, which explains the issue I was describing earlier. Also, I have tried downloading the file straight to my Google Drive, but have been unsuccessful.

Following your recommendation, I tried once again to download the dataset via the Google Drive option. After signing into my Gmail in the RLCMS webpage, I tried to download the version 2 data to my Google Drive and have waited for two hours or so, but unfortunately, I do not see any signs of progress. The only observable change in the RLCMS user tool is that there is a blank, light-red-colored bar at the top of the screen (kindly see image below), which I am now assuming means that there is some issue with the download. This is confirmed by the absence of the RLCMS map in my Google Drive.

Current RLCMS v2 screen:

<img width="960" alt="SERVIR-Mekong RLCMS" src="https://user-images.githubusercontent.com/43123250/97257049-bbf7e300-184f-11eb-8b8a-b5a335f945ec.PNG">

It may also be worth noting that before that light-red bar appeared, the following message appeared;

![SERVIR-Mekong RLCMS notice](https://user-images.githubusercontent.com/43123250/97257092-df229280-184f-11eb-92ae-c70dd5992fd2.png)

Thanks again @KMarkert , hope to hear from you soon.

**Comment by apoortinga** [comment]
Please use [this](https://code.earthengine.google.com/1cb8cc384d594078ea54c2e79ccd5e08) link to access the maps in earth engine directly. The old website might give some issues and we are working on the new website. Please visit our new website [here](https://landcovermapping.org/en/)

**Comment by j-johanness** [comment]
Hi @apoortinga , thank you very much for your reply! I tried using the new RLCMS website and it worked. I was able to download the land cover map for a single year at 30 m. However, instead of using the new website to download the data for all years, I plan to adapt the GEE script you shared so that I would be able to download the data in a more efficient manner. Thank you for sharing that script! I have tested it and verified that the pixel resolution is 30 m.

Before I proceed with the batch download, I would like to kindly ask 2 questions.

1. May I download and use the RLCMS map for 2018? I noticed that the RLCMS version 3 contains the land cover map for 2018, which is something that was not disclosed in the [Saah et al (2020) publication](https://www.sciencedirect.com/science/article/pii/S0303243419306270) in _Int J Appl Earth Obs Geoinf_ and the [RLCMS version 2](https://rlcms-servir.adpc.net/en/landcover/v2/#), both of which only contained land cover information up till 2017.

2. May I know what is the source of the administrative boundary vector layer that was used in the RLCMS? I am asking because the country outlines in the RLCMS vary slightly than the freely-available [Global Administrative boundaries (GADM boundaries) dataset](https://gadm.org/data.html) and the [Large Scale International Boundaries (LSIB) dataset ](https://developers.google.com/earth-engine/datasets/catalog/USDOS_LSIB_SIMPLE_2017) hosted in the GEE Data Catalog. I understand that this is partly due to the use of a buffered vector layer in GEE (`var mekongBuffer = ee.FeatureCollection ('ft:1LEGeqwlBCAlN61ie5ol24NdUDqB1MgpFR_sJNWQJ');`) and therefore am asking because I would like to use a suitable administrative boundary layer to complement the RLCMS maps.

Thank you kindly!

**Comment by apoortinga** [comment]
Hi Johanness, the 2018 was created using the same methods presented int the Saah et al. (2020) paper. We extracted the administrative boundaries of all 5 countries and added a buffer around those for exporting. We request users to use their own administrative boundaries.

**Comment by j-johanness** [comment]
Alright, thank you for clarifying! I will proceed to download the RLCMS from Earth Engine. Once again, thank you both @apoortinga and @KMarkert for helping me close this issue.
